" Denis Florjancic 2019-07-18
set nocompatible
filetype off	

set encoding=utf-8
syntax on "Syntax highlighting
let mapleader=","
set wildmenu

nnoremap <leader>d dd
nnoremap <C-n> :NERDTreeToggle<CR>

""" VUNDLE, PLUGINS SECTION

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" NERDTree and plugin for git status flags 
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

""" SETTING NUMBER SETTINGS

set number relativenumber " Set Hybrid line numbers

" Toggle between realtive and absolute numbers
:augroup numbertoggle
: autocmd!
: autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
: autocmd BufLeave,FocusLost,InsertEnter * set norelativenumber
:augroup END 

""" INDENTATION RULES
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

